## Preprocessing

In [20]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("./Resources/charity_data.csv")
application_df.head()

EIN                                      NAME APPLICATION_TYPE  \
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB              T10   
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR               T3   
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS               T5   
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION               T3   
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT               T3   

        AFFILIATION CLASSIFICATION      USE_CASE  ORGANIZATION  STATUS  \
0       Independent          C1000    ProductDev   Association       1   
1       Independent          C2000  Preservation  Co-operative       1   
2  CompanySponsored          C3000    ProductDev   Association       1   
3  CompanySponsored          C2000  Preservation         Trust       1   
4       Independent          C1000     Heathcare         Trust       1   

      INCOME_AMT SPECIAL_CONSIDERATIONS  ASK_AMT  IS_SUCCESSFUL  
0              0                      N     5000              1  
1         1-9999                      N   108590              1  
2              0                      N     5000              0  
3    10000-24999                      N     6692              1  
4  100000-499999                      N   142590              1

In [21]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(["EIN", "NAME"], axis = 1)
application_df.head()

APPLICATION_TYPE       AFFILIATION CLASSIFICATION      USE_CASE  \
0              T10       Independent          C1000    ProductDev   
1               T3       Independent          C2000  Preservation   
2               T5  CompanySponsored          C3000    ProductDev   
3               T3  CompanySponsored          C2000  Preservation   
4               T3       Independent          C1000     Heathcare   

   ORGANIZATION  STATUS     INCOME_AMT SPECIAL_CONSIDERATIONS  ASK_AMT  \
0   Association       1              0                      N     5000   
1  Co-operative       1         1-9999                      N   108590   
2   Association       1              0                      N     5000   
3         Trust       1    10000-24999                      N     6692   
4         Trust       1  100000-499999                      N   142590   

   IS_SUCCESSFUL  
0              1  
1              1  
2              0  
3              1  
4              1

In [22]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [23]:
# Look at APPLICATION_TYPE value counts for binning
application_df["APPLICATION_TYPE"].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [24]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = application_df["APPLICATION_TYPE"].unique()[ application_df["APPLICATION_TYPE"].value_counts() < 100 ]

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
Other      841
T7         725
T10        528
T9         156
T2          16
Name: APPLICATION_TYPE, dtype: int64

In [25]:
# Look at CLASSIFICATION value counts for binning
application_df["CLASSIFICATION"].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...  
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [26]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df["CLASSIFICATION"].value_counts()[ application_df["CLASSIFICATION"].value_counts() > 1 ]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [27]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = application_df["CLASSIFICATION"].unique()[ application_df["CLASSIFICATION"].value_counts() < 1000 ]

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     4040
C3000     1918
C2700      104
Name: CLASSIFICATION, dtype: int64

In [28]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df.head()

STATUS  ASK_AMT  IS_SUCCESSFUL  APPLICATION_TYPE_Other  \
0       1     5000              1                       0   
1       1   108590              1                       0   
2       1     5000              0                       0   
3       1     6692              1                       0   
4       1   142590              1                       0   

   APPLICATION_TYPE_T10  APPLICATION_TYPE_T19  APPLICATION_TYPE_T2  \
0                     1                     0                    0   
1                     0                     0                    0   
2                     0                     0                    0   
3                     0                     0                    0   
4                     0                     0                    0   

   APPLICATION_TYPE_T3  APPLICATION_TYPE_T4  APPLICATION_TYPE_T5  ...  \
0                    0                    0                    0  ...   
1                    1                    0                    0  ...   
2                    0                    0                    1  ...   
3                    1                    0                    0  ...   
4                    1                    0                    0  ...   

   INCOME_AMT_1-9999  INCOME_AMT_10000-24999  INCOME_AMT_100000-499999  \
0                  0                       0                         0   
1                  1                       0                         0   
2                  0                       0                         0   
3                  0                       1                         0   
4                  0                       0                         1   

   INCOME_AMT_10M-50M  INCOME_AMT_1M-5M  INCOME_AMT_25000-99999  \
0                   0                 0                       0   
1                   0                 0                       0   
2                   0                 0                       0   
3                   0                 0                       0   
4                   0                 0                       0   

   INCOME_AMT_50M+  INCOME_AMT_5M-10M  SPECIAL_CONSIDERATIONS_N  \
0                0                  0                         1   
1                0                  0                         1   
2                0                  0                         1   
3                0                  0                         1   
4                0                  0                         1   

   SPECIAL_CONSIDERATIONS_Y  
0                         0  
1                         0  
2                         0  
3                         0  
4                         0  

[5 rows x 45 columns]

In [29]:
# Split our preprocessed data into our features and target arrays
y = application_df["IS_SUCCESSFUL"].values
X = application_df.drop(["IS_SUCCESSFUL"], axis=1).values
print(X)
print(y)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=50)

[[       1     5000        0 ...        0        1        0]
 [       1   108590        0 ...        0        1        0]
 [       1     5000        0 ...        0        1        0]
 ...
 [       1     5000        0 ...        0        1        0]
 [       1     5000        0 ...        0        1        0]
 [       1 36500179        0 ...        0        1        0]]
[1 1 0 ... 0 1 0]


In [30]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [31]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 =  5
hidden_nodes_layer2 = 20
hidden_nodes_layer3 = 10

# First hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer1,
                             input_dim = number_input_features,
                             activation = "relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer2,
                             activation = "relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer3,
                             activation = "relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units = 1,
                             activation = "sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 5)                 225       
                                                                 
 dense_5 (Dense)             (None, 20)                120       
                                                                 
 dense_6 (Dense)             (None, 10)                210       
                                                                 
 dense_7 (Dense)             (None, 1)                 11        
                                                                 
Total params: 566
Trainable params: 566
Non-trainable params: 0
_________________________________________________________________


In [32]:
# Compile the model
nn.compile(loss = "binary_crossentropy",
           optimizer = "adam", 
           metrics = ["accuracy"])

In [33]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs = 100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6146 - accuracy: 0.6808
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5700 - accuracy: 0.7207
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5656 - accuracy: 0.7214
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5634 - accuracy: 0.7225
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5622 - accuracy: 0.7231
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5609 - accuracy: 0.7247
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5600 - accuracy: 0.7248
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5595 - accuracy: 0.7252
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5591 - accuracy: 0.7251
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5587 - accura

In [34]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5473 - accuracy: 0.7362 - 468ms/epoch - 2ms/step
Loss: 0.5472991466522217, Accuracy: 0.7362099289894104


In [35]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_optimization1.h5")

In [36]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 =  10
hidden_nodes_layer2 = 15
hidden_nodes_layer3 = 10

# First hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer1,
                             input_dim = number_input_features,
                             activation = "relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer2,
                             activation = "tanh"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer3,
                             activation = "relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units = 1,
                             activation = "sigmoid"))

# Check the structure of the model
print(nn.summary())

# Compile the model
nn.compile(loss = "binary_crossentropy",
           optimizer = "adam", 
           metrics = ["accuracy"])

# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs = 100)

# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_optimization2.h5")

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, 10)                450       
                                                                 
 dense_9 (Dense)             (None, 15)                165       
                                                                 
 dense_10 (Dense)            (None, 10)                160       
                                                                 
 dense_11 (Dense)            (None, 1)                 11        
                                                                 
Total params: 786
Trainable params: 786
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5930 - accuracy: 0.6995
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5660 

In [37]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 =  10
hidden_nodes_layer2 = 20
hidden_nodes_layer3 = 10

# First hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer1,
                             input_dim = number_input_features,
                             activation = "relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer2,
                             activation = "selu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer3,
                             activation = "relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units = 1,
                             activation = "sigmoid"))

# Check the structure of the model
print(nn.summary())

# Compile the model
nn.compile(loss = "binary_crossentropy",
           optimizer = "adam", 
           metrics = ["accuracy"])

# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs = 125)

# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_optimization3.h5")

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 10)                450       
                                                                 
 dense_13 (Dense)            (None, 20)                220       
                                                                 
 dense_14 (Dense)            (None, 10)                210       
                                                                 
 dense_15 (Dense)            (None, 1)                 11        
                                                                 
Total params: 891
Trainable params: 891
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/125
804/804 [==============================] - 3s 2ms/step - loss: 0.5955 - accuracy: 0.7018
Epoch 2/125
804/804 [==============================] - 2s 2ms/step - loss: 0.5679 